name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'image/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '26.3'
          - 'snapshot'
        cask_version:
          - '0.8.4'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Install cask
        run: |
          git clone https://github.com/cask/cask ~/.cask
          echo "::add-path::${HOME}/.cask/bin"
      - name: Run tests
        run: make test
